-- CreateTable
CREATE TABLE `Client` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `intakeQKey` VARCHAR(191) NOT NULL,
    `intakeQBaseUrl` VARCHAR(191) NOT NULL DEFAULT 'https://intakeq.com/api/v1',
    `vtigerUrl` VARCHAR(191) NOT NULL,
    `vtigerUsername` VARCHAR(191) NULL,
    `vtigerAccessKey` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Client_name_key`(`name`),
    INDEX `Client_name_idx`(`name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Lead` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `clientId` INTEGER NOT NULL,
    `vtigerId` VARCHAR(191) NOT NULL,
    `lead_no` VARCHAR(191) NULL,
    `salutationtype` VARCHAR(191) NULL,
    `firstname` VARCHAR(191) NULL,
    `lastname` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `phone` VARCHAR(191) NULL,
    `mobile` VARCHAR(191) NULL,
    `secondaryemail` VARCHAR(191) NULL,
    `fax` VARCHAR(191) NULL,
    `company` VARCHAR(191) NULL,
    `designation` VARCHAR(191) NULL,
    `industry` VARCHAR(191) NULL,
    `website` VARCHAR(191) NULL,
    `leadsource` VARCHAR(191) NULL,
    `leadstatus` VARCHAR(191) NULL,
    `annualrevenue` VARCHAR(191) NULL,
    `rating` VARCHAR(191) NULL,
    `noofemployees` VARCHAR(191) NULL,
    `assigned_user_id` VARCHAR(191) NULL,
    `source` VARCHAR(191) NULL DEFAULT 'WEBSERVICE',
    `starred` VARCHAR(191) NULL,
    `tags` VARCHAR(191) NULL,
    `lane` VARCHAR(191) NULL,
    `code` VARCHAR(191) NULL,
    `city` VARCHAR(191) NULL,
    `country` VARCHAR(191) NULL,
    `state` VARCHAR(191) NULL,
    `pobox` VARCHAR(191) NULL,
    `cf_883` VARCHAR(191) NULL,
    `cf_941` VARCHAR(191) NULL,
    `cf_943` VARCHAR(191) NULL,
    `description` TEXT NULL,
    `emailoptout` VARCHAR(191) NULL DEFAULT '0',
    `createdtime` VARCHAR(191) NULL,
    `modifiedtime` VARCHAR(191) NULL,
    `modifiedby` VARCHAR(191) NULL,
    `rawData` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Lead_vtigerId_key`(`vtigerId`),
    INDEX `Lead_clientId_idx`(`clientId`),
    INDEX `Lead_email_idx`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Appointment` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `clientId` INTEGER NOT NULL,
    `intakeQId` VARCHAR(191) NOT NULL,
    `clientName` VARCHAR(191) NULL,
    `clientEmail` VARCHAR(191) NULL,
    `clientPhone` VARCHAR(191) NULL,
    `clientDateOfBirth` VARCHAR(191) NULL,
    `intakeQClientId` INTEGER NULL,
    `status` VARCHAR(191) NULL,
    `startDate` BIGINT NULL,
    `endDate` BIGINT NULL,
    `duration` INTEGER NULL,
    `serviceName` VARCHAR(191) NULL,
    `serviceId` VARCHAR(191) NULL,
    `locationName` VARCHAR(191) NULL,
    `locationId` VARCHAR(191) NULL,
    `price` DOUBLE NULL,
    `practitionerName` VARCHAR(191) NULL,
    `practitionerEmail` VARCHAR(191) NULL,
    `practitionerId` VARCHAR(191) NULL,
    `startDateIso` VARCHAR(191) NULL,
    `endDateIso` VARCHAR(191) NULL,
    `startDateLocal` VARCHAR(191) NULL,
    `endDateLocal` VARCHAR(191) NULL,
    `startDateLocalFormatted` VARCHAR(191) NULL,
    `invoiceId` VARCHAR(191) NULL,
    `invoiceNumber` INTEGER NULL,
    `clientNote` TEXT NULL,
    `practitionerNote` TEXT NULL,
    `telehealthInfo` JSON NULL,
    `intakeId` VARCHAR(191) NULL,
    `dateCreated` BIGINT NULL,
    `createdBy` VARCHAR(191) NULL,
    `bookedByClient` BOOLEAN NULL,
    `lastModified` BIGINT NULL,
    `attendanceConfirmationResponse` VARCHAR(191) NULL,
    `reminderType` VARCHAR(191) NULL,
    `placeOfService` VARCHAR(191) NULL,
    `fullCancellationReason` TEXT NULL,
    `cancellationReasonNote` TEXT NULL,
    `cancellationDate` VARCHAR(191) NULL,
    `customFields` JSON NULL,
    `additionalClients` JSON NULL,
    `rawData` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Appointment_intakeQId_key`(`intakeQId`),
    INDEX `Appointment_clientId_idx`(`clientId`),
    INDEX `Appointment_clientEmail_idx`(`clientEmail`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Lead` ADD CONSTRAINT `Lead_clientId_fkey` FOREIGN KEY (`clientId`) REFERENCES `Client`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Appointment` ADD CONSTRAINT `Appointment_clientId_fkey` FOREIGN KEY (`clientId`) REFERENCES `Client`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
